apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eaa69mcde-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eaa69mcde-go 
  name: eaa69mcde-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eaa69mcde-go 
